spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/graduateam?unixSocket=/tmp/mysql.sock
    username: graduateam
    password: "graduateam!"
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  logging:
    level:
      org.springframework: DEBUG