name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: graduateam
          MYSQL_USER: graduateam
          MYSQL_PASSWORD: graduateam!
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 -ugraduateam -pgraduateam!" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Wait for MariaDB to be ready
        run: |
          for i in {1..30}; do
            nc -z localhost 3306 && echo "MariaDB is up" && exit 0
            echo "Waiting for MariaDB..."
            sleep 2
          done
          echo "MariaDB did not start in time" && exit 1

      - name: Check MariaDB status
        run: docker ps -a

      - name: Check MariaDB logs
        run: docker logs $(docker ps -q --filter ancestor=mariadb:11.7)

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon